### ISSUE TITLE
seajs相关

### ISSUE THREAD

**Issue by Mcbai** [lichunqiang/gulp-tmod#10]
请问该插件能生成seajs所能使用的JS文件吗

**Comment by lichunqiang** [comment]
具体可以看下 https://github.com/aui/tmodjs中的描述，seajs 要能用的话关键是打包压缩后的，需要指定id，才行，不知道现在seajs的是怎么样的

**Comment by Mcbai** [comment]
昨天下午已经找到解决办法了，手动添加tmodjs的package.json文件到模板目录，就像直接使用tmod一样手动修改package.json的配置，只不过直接使用tmod会自动生成package.json文件，使用gulp-tmod插件需要手动添加
