### ISSUE TITLE
插件不规范吧？怎么能把输出目录直接写到选项里面？

### ISSUE THREAD

**Issue by Lynn-cc** [lichunqiang/gulp-tmod#11]
gulp不是应该返回流么？但是这个插件只能在选项里写好输出目录直接就输出成文件了。。。导致不能和其他插件兼容做更多自定义处理，比如：文件名名字自定义，后续文件合并等等。
除非确实是只需要输出js文件自己去引用的那种才能正常使用。。。

**Comment by calledT** [comment]
给作者提了PR，不过因为[tmodjs](https://github.com/aui/tmodjs)的接口对[gulp](https://github.com/gulpjs/gulp) 插件开发并不友好，像`combo`为`false`时并不会生出基础的template.js，需要自己下载一个，而且tmodjs并不能关闭原来的output，所以设置了一个隐藏的文件夹来存放output。对于`compress `和`minify `应该由其它插件去完成，在这里设置也是无效的。

**Comment by lichunqiang** [comment]
Resolved in  eaea3c969ee7613da483a89e373c3aceefb4cd0c
