### ISSUE TITLE
使用gulp-tomd,编译的html文件超过16个时,不生成template.js文件，且后台无任何错误信息

### ISSUE THREAD

**Issue by lrdbzs** [lichunqiang/gulp-tmod#12]
使用gulp-tomd,编译的html文件超过16个时,不生成template.js文件，且后台无任何错误信息

**Comment by landy2014** [comment]
暂时还未能找到原因。

**Comment by calledT** [comment]
更新到最新版本，查看这个[例子](https://github.com/calledT/gulp-tmod-demo)
