### ISSUE TITLE
combo后的template文件格式报错

### ISSUE THREAD

**Issue by landy2014** [lichunqiang/gulp-tmod#17]
我在gulp里面这样用：
gulp.task("test", funttion(){ 
return gulp.src(["template/comment/*.html"])
                .pipe(tmodjs({
                    "templateBase": "./template/comment",
                    "combo": true,
                    "cache": false,
                    "minify" : true,
                    "runtime": "tempcomment.js",
                    "syntax": "native"
                }))
                .pipe(gulp.dest("./lib/template"));

});

然后在seajs模块里面如此引用：
var template = require("../template/tempcomment.js");

然后使用seajs的打包工具进行打包。报错：

gulp-notify: [Error running Gulp] Error: /www/frontend/bdplatform/src/bd/lib/page/index.js: Unexpected token keyword «else», expected punc «,»

本来我以为是index.js的错误。但是去掉
var template = require("../template/tempcomment.js"); 
无报错。

而我gulp里面改为如下：
gulp.task("test", funttion(){ 
return gulp.src(["template/comment/*.html"])
                .pipe(tmodjs({
                    "templateBase": "./template/comment",
                    "combo": true,
                    "cache": false,
                    "minify" : true,
                    "runtime": "tempcomment.js",
                    "syntax": "native"
                }))
                .pipe(uglify({
                        output : {
                             beautify : true
                      }
                  }))
                .pipe(gulp.dest("./lib/template"));

});

则无报错。

不知道是什么错误

**Comment by calledT** [comment]
这个插件的runtime输出没有经过[tmodjs里面的uglify](https://github.com/aui/tmodjs/blob/master/src/tmod.js#L721),所以应该是tomdjs自身的问题。

**Comment by landy2014** [comment]
嗯，了解。
