### ISSUE TITLE
新版本v2.0.3使用问题

### ISSUE THREAD

**Issue by janjangao** [lichunqiang/gulp-tmod#18]
换成新版本后，我发现所有的模板会编译成一个template.js，以前基础库和模板编译的js是分开的，现在合成了一起成为template.js，那我在代码里如何引用呢，commonjs的引入方式

以前使用方式：
var testTpl = require('./tpl/test')
testTpl(data)

现在合并在一起了，module.exports应该只能导出一个模板function，现在的引用方式能在文档写下吗？arttemplate也用了两年多了，突然的版本升级有点没缓过来

**Comment by lichunqiang** [comment]
ping @calledT

**Comment by landy2014** [comment]
其实combo后和之前的引用方式变化只是多了目录引用。
假设如下目录结构：
      template
            -test
                 - test.html
而构建中使用如下进行构建：
gulp.task("tomd",function(){
       Gulp.src("template/*_/_.html")
.pipe(tmodjs({
            Templatebase : "template"
         })
.pipe(gulp.dest("./dest"));

那么在commonjs引入模块后，使用方式为：
Var template = require("./dest/template.js");

Template("test/test");

**Comment by calledt** [comment]
[gulp-tmod-demo](https://github.com/calledT/gulp-tmod-demo)看这个demo，选择自己想要的`type`类型。

**Comment by janjangao** [comment]
非常感谢楼上各位
