### ISSUE TITLE
编译之后，模块名称的问题。

### ISSUE THREAD

**Issue by anyone-yuren** [lichunqiang/gulp-tmod#20]
![image](https://cloud.githubusercontent.com/assets/14817820/16612365/39f2d02a-4399-11e6-9913-061594439fbd.png)
编译后的文件变成这样子的路径了，怎么破！！！！

**Comment by calledt** [comment]
设置`templatebase`为`gulp-fruit/tpls`。

**Comment by anyone-yuren** [comment]
追加提问下，如果我是照默认的type编译完成的，那么js我改如何引用呢？好像跟tmodJs工具本身不太一样，能详细解释下吗？谢谢

**Comment by calledt** [comment]
[gulp-tmod-demo](https://github.com/calledT/gulp-tmod-demo)

**Comment by TNT-Likely** [comment]
遇到同样的问题,用tmodjs命令行输出的就是对的，设置templatebase无效
